apiVersion: v2
name: vara-wiki
description: Vara documentation wiki
type: application
version: 1.0.0
appVersion: "1.0.0"

maintainers:
  - name: DevOps Team
    email: devops@example.com

sources:
  - https://github.com/example-org/vara-wiki

dependencies:
  - name: gearLib
    repository: file://../../lib/gearLib
    version: 1.0.0
